### ISSUE TITLE
Type/schema identification 

### ISSUE THREAD

**Issue by joostholslag** [SevKohler/OMOCL#10]
It would be good to have some kind of identification of the kind of yaml in the file. Stating this is an OMOCL openEHR to OMOP mapping file. Ideally by referencing a schema as requested in #9.

**Comment by SevKohler** [comment]
Yeah its in the new header for both fhirConnect and OMOCL will be:
```
environment:
   version: 0.0.1a
   format:
     system: OMOCL
     version: v0.01
   target:
     system: CDM
     version: 5.4

openEhrConfig:
   archetype: "openEHR-EHR-INSTRUCTION.medication_order.v2"
   revision_min: #optional
   revision_max: #optional
   
```
I will try to add it asap to the new version of OMOCL.
